### ISSUE TITLE
The minskins review 06/22

### ISSUE THREAD

**Issue by AdfPizarro** [carlosveigadev/HTML-CSS-Capstone-Project#1]
Your project looks great so far

-You can merge the media queries in the same file
-Remember to check the html validator before submit 
-Check the unused row class, you can make it a flex container
-Check the order you have in the css imports

You habe become a powerfull wizzard 

Hassan says - Your readme is not that bad -
<pre>
                           ,---.
                          /    |
                         /     |
                        /      |
                       /       |
                  ___,'        |
                <  -'          :
                 `-.__..--'``-,_\_
                    |o/ <o>` :,.)_`>
                    :/ `     ||/)
                    (_.).__,-` |\
                    /( `.``   `| :
                    \'`-.)  `  ; ;
                    | `       /-<
                    |     `  /   `.
    ,-_-..____     /|  `    :__..-'\
   /,'-.__\\  ``-./ :`      ;       \
   `\ `\  `\\  \ :  (   `  /  ,   `. \
     \` \   \\   |  | `   :  :     .\ \
      \ `\_  ))  :  ;     |  |      ): :
     (`-.-'\ ||  |\ \   ` ;  ;       | |
      \-_   `;;._   ( `  /  /_       | |
       `-.-.// ,'`-._\__/_,'         ; |
          \:: :     /     `     ,   /  |
           || |    (        ,' /   /   |
           ||                ,'   /    |
</pre>

**Comment by carlosveigadev** [comment]
Thanks guys!
I improve the code as suggested.
